steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --update-labels
      - environment=${_ENVIRONMENT}
      - --set-env-vars
      - ENVIRONMENT=${_ENVIRONMENT}
      - --set-secrets
      - PAID_OPENAI_API_KEY=PAID_OPENAI_API_KEY:latest

substitutions:
  _REGION: us-central1
  _SERVICE_NAME: business-intelligence
  _AR_REPO: business-intelligence
  _IMAGE_NAME: insightforge
  _ENVIRONMENT: prod
